"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. The isolated runtime, the embedded package
modules (pipeline.py, sample_data.py, samples.py, metrics.py, head_selection.py), and the model
pin/stage/verify cells are produced by the generator from repository sources so they cannot drift
from the package.

This template configures an E2E species-classification workflow: the pinned BioCLIP 2 snapshot is
digest-verified, 48 embedded CC0 iNaturalist photographs of four sparrow species are validated and
split, image embeddings and zero-shot species classification are run, trivial baselines are
measured, a linear head initialised from the zero-shot classifier is fine-tuned with a predeclared
learning-rate grid and validation selection, and the adapter is exported and reloaded.

Review fixes (Notebook Review Framework v1, review PR #10, BIO-M1..M5 / BIO-m1..m6): the runtime is the
fleet's uv isolated environment (no in-kernel install, no restart); head fine-tuning selects its
learning rate and epoch on validation with epoch 0 (zero-shot) eligible and reports how far the head
moved (the capstone's BC-M1 fix, carried in `head_selection.py` because the capstone carries
`pipeline.py` byte for byte); BYOD loads folder zips, enforces its real minimum in Section 4 and
recovers from bad or repeated uploads; and the guided layer (how to use, roadmap, predictions, worked
answers, a change-one-thing activity, troubleshooting, glossary, conclusion) is added.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

REPO = "bioclip2-biodiversity-pipeline"

BADGES = [
    (
        "GitHub",
        "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
        f"https://github.com/kurtvalcorza/{REPO}",
    ),
    (
        "Open In Colab",
        "https://colab.research.google.com/assets/colab-badge.svg",
        f"https://colab.research.google.com/github/kurtvalcorza/{REPO}/blob/main/tutorials/bioclip2_biodiversity_colab.ipynb",
    ),
    (
        "Hugging Face",
        "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-imageomics%2Fbioclip--2-ffcc4d?style=flat",
        "https://huggingface.co/imageomics/bioclip-2",
    ),
    (
        "Upstream",
        "https://img.shields.io/badge/Upstream-Imageomics%2Fbioclip--2-181717?style=flat&logo=github&logoColor=white",
        "https://github.com/Imageomics/bioclip-2",
    ),
    ("arXiv", "https://img.shields.io/badge/arXiv-2505.23883-b31b1b.svg", "https://arxiv.org/abs/2505.23883"),
]

TEMPLATE = {
    "package": "bioclip2_biodiversity_pipeline",
    "repo_name": REPO,
    "stem": "bioclip2_biodiversity",
    "notebook_name": "bioclip2_biodiversity_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (ast-audio-classification-pipeline and this repository's capstone):
    # managed CPython, a size- and SHA-256-verified uv wheel, and a lock compiled from the pyproject pins with
    # `uv pip compile pyproject.toml --python-version 3.12 --python-platform x86_64-manylinux_2_28 --generate-hashes
    # --only-binary :all: -o tutorials/requirements-colab.lock.txt`.
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated environment from the hash-locked pins (the "
        "kernel's own packages are left alone, so no restart is needed), stages and digest-verifies the pinned BioCLIP 2 "
        "snapshot (3 files, 1.71 GB), builds the CLIP model from the pinned config and loads the weights strictly, decodes "
        "the 48 CC0 iNaturalist sparrow photographs carried inside this notebook (no dataset download), validates the image "
        "and dataset contracts, splits them into stratified train/validation/test sets, shows what the input validation "
        "rejects, computes image embeddings and checks they are reproducible, classifies the test split zero-shot from "
        "scientific names (the model's own prior), measures a majority-class and a colour baseline, fine-tunes a linear head "
        "initialised from the zero-shot classifier with a predeclared learning-rate grid whose rate and epoch are chosen on "
        "the validation split (epoch 0, the zero-shot classifier itself, can win), evaluates accuracy, macro-F1 and AUROC on "
        "the held-out test split, classifies six held-out images as new inputs, exports the adapter as safetensors with a "
        "manifest, reloads that artifact into a fresh pipeline to verify prediction parity, and runs one change-one-thing "
        "activity on features already computed. The default path needs no repository clone, no DIMER worker or service, no "
        "credential, no upload dialog and no configuration edit (NOTEBOOK_SPEC 2.2 §5). A CUDA runtime is used automatically "
        "when present. Timings: the code cells of this version took 71 s on a local Windows CPU check (24 threads, PyTorch 2.11 CPU build rather than the pinned 2.14, "
        "float32, snapshot pre-staged, environment pre-installed); the previous version's Kaggle Tesla T4 run took 265.3 s "
        "including the 1.71 GB download. No hosted run of this version is recorded yet, so on a hosted CPU runtime expect "
        "roughly the local CPU figure (an estimate). Building the isolated environment and downloading the checkpoint come on "
        "top of these."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4 and put one scientific name per label in "
        "`BYOD_CLASS_PROMPTS` (a JSON object, for example `{\"song_sparrow\": \"Melospiza melodia\"}`), then select that cell "
        "and choose **Runtime → Run after** (it re-runs Section 4 and every later cell). Leave `BYOD_PATH` empty to get an "
        "upload dialog (Colab only), or set it to a `.zip`, a folder or a `.csv`/`.json`/`.jsonl` file already in this "
        "runtime. Supply labelled organism photographs as a zip of `<label>/<image>` folders (one enclosing folder is "
        "allowed), or a zip holding a CSV (`id,image,label`), a JSON array or a JSONL file with image paths relative to it. "
        "With the default fractions you need at least **5 photographs per class** (7 per class when there are only two "
        "classes); Section 4 computes this minimum, checks it before any model runs and names the class it refuses. Every "
        "upload replaces the previous one. Your photographs pass through the same image validation, stratified split, "
        "zero-shot and trivial baselines, adaptation, held-out evaluation, inference, artifact export and reload-parity "
        "cells as the sample. The expected layout and the image ceilings are stated in the Prerequisites and in Section 4, "
        "and uploaded files stay inside this runtime. BYOD is optional and never part of the default path."
    ),
    "pipeline_class": "BioClip2Pipeline",
    "weights_key": "bioclip-2",
    "modules": ["pipeline.py", "sample_data.py", "samples.py", "metrics.py", "head_selection.py"],
    "entry_module": "pipeline.py",
    "runtime_imports": ["torch", "open_clip", "safetensors"],
    "title": "BioCLIP 2 — DIMER E2E species-classification tutorial (standalone)",
    "badges": BADGES,
    "capability": "zero-shot species classification, organism image embeddings and bounded species-classification fine-tuning",
    "intro": (
        "BioCLIP 2 is a vision-language foundation model for organismal biology: a CLIP model (ViT-L/14 image tower, 12-layer "
        "text tower, 768-dimensional joint space) trained by the Imageomics Institute on TreeOfLife-200M — about 214 million "
        "images covering 952 thousand taxa — with hierarchical contrastive learning over taxonomic names. Because images and "
        "taxon names share one space, it can classify a photograph against **any** list of species names with no training at "
        "all, and the upstream paper reports that this scaled training also produces representations that separate traits and "
        "ecological attributes it was never told about.\n\n"
        "This tutorial exercises three things on real field data. The dataset is 48 photographs — 12 each of four North American "
        "sparrow species — from research-grade iNaturalist observations whose photos carry the CC0 licence, carried inside this "
        "notebook. The four species were chosen **before any result was seen** to make colour a weak cue: all four are streaked "
        "grey-brown birds, so a colour baseline has little to use and any separation comes from finer structure. First the model "
        "classifies them zero-shot from scientific names; then a linear head is fine-tuned starting *from* that zero-shot "
        "classifier, so every number after training is directly comparable to the number before it. The head's learning rate "
        "and epoch are chosen on the validation split from a grid fixed in advance, and epoch 0 — the zero-shot classifier "
        "itself — is one of the candidates, so the notebook can honestly report that training changed nothing.\n\n"
        "**Who this is for.** A learner who knows basic Python and has met the idea of image classification, and wants to see "
        "how a vision-language model classifies species without training, how to check what that result means, and how to "
        "adapt it carefully to a small labelled set. No prior experience with CLIP, BioCLIP or fine-tuning is assumed; each "
        "term is explained where it is first used and again in the **Glossary** at the end.\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Zero-shot classification | Embedding | Head fine-tuning |\n"
        "|---|---|---|---|\n"
        "| Input | 1..32 photographs and one name per class | 1..32 photographs | labelled photographs (28 training, 8 validation in the sample) |\n"
        "| Model | image tower and text tower, scaled cosine similarity | the image tower | a linear head on the frozen image tower, started at the zero-shot classifier |\n"
        "| Output | per photograph: a label and softmax scores over *your* label set | one unit-length 768-d vector per photograph | an adapter (safetensors) and held-out accuracy / macro-F1 / AUROC |\n\n"
        "**How to use this notebook.** Choose a runtime (a GPU runtime is faster; CPU works), then **Runtime → Run all**. "
        "Sections 1–3 are **infrastructure** — the isolated environment, the carried code and the model verification — and "
        "can be run without study. The learning path starts in Section 4. Form fields (`# @param`) are the only values meant "
        "to be edited; the defaults reproduce the recorded path. Each stage states what it does and asks you to **predict** "
        "before it runs; the next cell opens with **What to notice** and a collapsible **Check your reasoning** block with a "
        "worked answer. Each optional experiment names the field to change and the cells to re-run. Section 13 is a "
        "**change-one-thing activity**. **Troubleshooting**, a **Glossary** and a **Conclusion** template are at the end. Your "
        "notes are optional and are not required submissions.\n\n"
        "**Roadmap:** 4 load, validate and split the photographs → 5 what validation refuses → 6 embeddings → 7 zero-shot "
        "classification and what its scores mean → 8 the baselines that know nothing about birds → 9 fine-tune the head, "
        "choosing the rate on validation → 10 held-out evaluation against zero-shot → 11 classify new images, export and "
        "reload → 12 provenance → 13 **change one thing: uninformative class names** → conclude."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *photograph + class names → two towers → softmax over your names* and "
        "say why a confident zero-shot score on a blank image is not evidence of a bird (Section 7); (2) explain from Section "
        "8's numbers why the colour baseline sits near chance on these four species; (3) explain why the fine-tuned head "
        "starts at the zero-shot classifier and why validation, never test, chooses its learning rate and epoch (Section 9); "
        "(4) read the head-displacement and zero-shot-agreement numbers and say whether training changed the classifier "
        "(Sections 9–10); (5) predict and then measure how much fine-tuning recovers when the class names carry no "
        "information (Section 13); and (6) check that an exported adapter reproduces the evaluated model (reload parity, "
        "Section 11)."
    ),
    "exclusions": (
        "the published BioCLIP 2 benchmarks (NABirds, Rare Species, Meta-Album, NeWT, FishNet and the rest), open-set or "
        "hierarchical (genus/family) prediction, image-to-image retrieval at scale, the newer `imageomics/bioclip-2.5-vith14` "
        "checkpoint, and any claim that a photograph shows what its label says. The repository exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and Colab or Jupyter familiarity; no prior experience with CLIP or fine-tuning. The notebook explains zero-shot classification, the logit scale, embeddings, the softmax score (and why it is not a calibrated probability), macro-F1 and AUROC where they are first used; the Glossary repeats them. It helps to know what a scientific (binomial) name is.",
        "- **Runtime:** a fresh **Linux x86_64** runtime — Google Colab, Kaggle or Linux Jupyter. Section 1 builds its own Python 3.12.12 environment from a hash-locked list of manylinux wheels, so the kernel's own Python version does not matter, and a Windows or macOS kernel is not supported (Section 1 stops with that message). CPU is enough, and CUDA is used automatically when present. The locked install (PyTorch 2.14.0 with its CUDA libraries) and the 1.71 GB snapshot are the large downloads. Measured on a local Windows CPU check of this version (24 threads, float32, snapshot pre-staged): about 0.25 s per image for the embedding passes and 10 s for Section 9's learning-rate grid. No hosted CPU run is recorded; expect figures of the same order there (an estimate).",
        "- **No remote code:** the checkpoint is a plain safetensors state dict loaded strictly into `open_clip`'s own CLIP module, built from the pinned `open_clip_config.json`. Nothing from the Hub is executed.",
        "- **Data contract:** records are `{id, image_bytes, label}` in memory; images are JPEG, PNG or WEBP with a shorter side of at least 32 px and a longer side of at most 8192 px, decoded to RGB and centre-cropped to 224x224 by the CLIP transform; unique ids and unique image bytes; 2..50 classes. Adaptation needs at least 3 training photographs per class and 8 in total, so with the default split fractions (20 % validation, 25 % test) a dataset needs at least **5 photographs per class**, or 7 per class when there are only two classes; Section 4 computes this from the fractions you set and refuses a smaller class before any model runs. BYOD accepts a zip of `<label>/<image>` folders (one enclosing folder is allowed) or a CSV/JSON/JSONL of image paths; `.jpg` files that are really MPO (multi-picture) files are refused with the conversion to apply.",
        "- **Validation is decoding, not biology:** nothing checks that a photograph shows an organism, that it fills the frame, or that a label names a real taxon. A photo of a rock is embedded and classified without complaint.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there. Location metadata is the sensitive part of a biodiversity record — the sample carries none. Under BYOD, Section 4 copies your photographs unchanged into `outputs/byod/images/` (so the written CSV reloads) and warns when any of them carries an EXIF GPS block; remove `outputs/byod/` before you share `outputs/`. The default path uploads nothing.",
    ],
    "cells": [
        {
            "md": (
                "## 4. Sample photographs, validation and split\n\n"
                "The default dataset is carried inside this notebook: 48 JPEG photographs, 224x224, decoded from base64 in the "
                "`sample_data` module above, each traceable to its iNaturalist observation (the observation URL, photo id and "
                "observer login are recorded; the CC0 licence code was checked per photo when the set was built; no location was "
                "collected). `validate_dataset` decodes every image — that is the check — and reports sizes, class counts, the "
                "ceilings and a dataset digest before any model runs. `split_dataset` shuffles within each class and cuts 20 % "
                "validation / 25 % test; the sample keeps one photo per observer within a species, which is what makes a random "
                "split defensible here. It also refuses a class that would leave fewer than 3 training photographs, naming the "
                "class and the minimum per class for the fractions you chose (`minimum_records_per_class`).\n\n"
                "**Bring your own data:** set `USE_BYOD = True` and `BYOD_CLASS_PROMPTS` to a JSON object with exactly one "
                "scientific name per label, either leave `BYOD_PATH` empty to get an upload dialog (Colab only) or set it to a "
                "`.zip`, a folder or a `.csv`/`.json`/`.jsonl` file already in this runtime, then select this cell and choose "
                "**Runtime → Run after**. Each upload replaces the previous one (`work/byod` is emptied first). A zip is refused "
                "before anything is written if a member would land outside `work/byod`, is a symbolic link, or the archive "
                "expands beyond 2 GB or 20,000 members. Your dataset table and copies of your photographs are written to `outputs/byod/` "
                "(replaced on every upload); the sample's go to `outputs/{stem}_sample_dataset.csv` and `outputs/images/`.\n\n"
                "Look for: 48 images, four classes, 12 each, splits 28/8/12, the per-class minimum, the contact sheet, and a "
                "written dataset CSV with an `images/` folder beside it — the BYOD shape. The photographs are unfiltered beyond "
                "licence and quality grade: some birds are small in the frame, one is held in a hand. That is what field data "
                "looks like.\n\n"
                "**Predict before running:** with 12 photographs per species and these fractions, how many of each species go to "
                "validation, test and training? What is the smallest number per species that would still work?"
            ),
            "code": (
                "import io\n"
                "import json\n"
                "import os\n"
                "import shutil\n"
                "import stat\n"
                "import zipfile\n"
                "from pathlib import Path\n\n"
                "from PIL import Image\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "BYOD_CLASS_PROMPTS = '{{}}'  # @param {{type:\"string\"}}\n"
                "VAL_FRACTION = 0.2  # @param {{type:\"number\"}}\n"
                "TEST_FRACTION = 0.25  # @param {{type:\"number\"}}\n"
                "SEED = 42  # @param {{type:\"integer\"}}\n\n"
                "MAX_ZIP_MEMBERS = 20_000\n"
                "MAX_ZIP_BYTES = 2_000_000_000\n\n"
                "def extract_zip(payload, root):\n"
                "    \"\"\"Extract an uploaded zip under root, refusing the whole archive before writing anything unsafe.\"\"\"\n"
                "    base = root.resolve()\n"
                "    with zipfile.ZipFile(io.BytesIO(payload)) as zf:\n"
                "        members = zf.infolist()\n"
                "        if len(members) > MAX_ZIP_MEMBERS or sum(m.file_size for m in members) > MAX_ZIP_BYTES:\n"
                "            raise ValueError(f'the zip holds {{len(members)}} members and expands to {{sum(m.file_size for m in members)}} bytes; the limits are {{MAX_ZIP_MEMBERS}} members and {{MAX_ZIP_BYTES}} bytes')\n"
                "        for member in members:\n"
                "            if stat.S_ISLNK(member.external_attr >> 16):\n"
                "                raise ValueError('zip member is a symbolic link, which is not accepted: ' + member.filename)\n"
                "            target = (root / member.filename).resolve()\n"
                "            if target == base or not target.is_relative_to(base):\n"
                "                raise ValueError('zip member escapes the upload directory, so nothing was extracted: ' + member.filename)\n"
                "        for member in members:\n"
                "            if not member.is_dir():\n"
                "                target = (root / member.filename).resolve()\n"
                "                target.parent.mkdir(parents=True, exist_ok=True)\n"
                "                target.write_bytes(zf.read(member))\n"
                "    tables = sorted(p for p in root.rglob('*') if p.suffix.lower() in ('.csv', '.json', '.jsonl') and '__MACOSX' not in p.parts)\n"
                "    if len(tables) > 1:\n"
                "        raise ValueError('the zip holds more than one dataset table; keep exactly one of: ' + ', '.join(str(t.relative_to(root)) for t in tables))\n"
                "    return tables[0] if tables else root\n\n"
                "def has_location(payload):\n"
                "    try:\n"
                "        return bool(Image.open(io.BytesIO(payload)).getexif().get(0x8825))\n"
                "    except Exception:\n"
                "        return False\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "if USE_BYOD:\n"
                "    try:\n"
                "        class_prompts = json.loads(BYOD_CLASS_PROMPTS)\n"
                "    except json.JSONDecodeError as exc:\n"
                "        raise ValueError('BYOD_CLASS_PROMPTS must be a JSON object such as {{\"song_sparrow\": \"Melospiza melodia\"}}: ' + str(exc)) from None\n"
                "    if not isinstance(class_prompts, dict) or not all(isinstance(k, str) and isinstance(v, str) and v.strip() for k, v in class_prompts.items()):\n"
                "        raise ValueError('BYOD_CLASS_PROMPTS must map each label (a string) to a non-empty scientific name (a string)')\n"
                "    byod_root = Path('work') / 'byod'\n"
                "    if byod_root.exists():\n"
                "        shutil.rmtree(byod_root)  # a new upload never reads files left by an earlier one\n"
                "    byod_root.mkdir(parents=True)\n"
                "    if BYOD_PATH.strip():\n"
                "        source = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not source.exists():\n"
                "            raise FileNotFoundError(f'BYOD_PATH = {{BYOD_PATH!r}} does not exist in this runtime: fix the path, or leave BYOD_PATH empty to upload a file in Colab.')\n"
                "        file_name = source.name\n"
                "        if source.is_file() and source.suffix.lower() == '.zip':\n"
                "            byod_source = extract_zip(source.read_bytes(), byod_root)\n"
                "        else:\n"
                "            byod_source = source\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError('The upload dialog needs Google Colab. Elsewhere, put the .zip (or folder) in this runtime and set BYOD_PATH to its path.') from None\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise RuntimeError(f'Upload exactly one .zip file (received {{len(uploaded)}}). Run this cell again and choose a file, or set BYOD_PATH to a file already in this runtime.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        if file_name.lower().endswith('.zip'):\n"
                "            byod_source = extract_zip(payload, byod_root)\n"
                "        else:\n"
                "            byod_source = byod_root / Path(file_name).name\n"
                "            byod_source.write_bytes(payload)\n"
                "    records = load_byod_dataset(byod_source)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    dataset_csv = 'outputs/byod/{stem}_byod_dataset.csv'\n"
                "    shutil.rmtree('outputs/byod', ignore_errors=True)  # your photographs live only here; a new upload replaces them\n"
                "else:\n"
                "    records = generate_sample_dataset()\n"
                "    data_source = 'embedded CC0 iNaturalist sample (' + str(SAMPLE_SIZE) + ' photographs, four sparrow species)'\n"
                "    class_prompts = dict(SAMPLE_CLASS_PROMPTS)\n"
                "    dataset_csv = 'outputs/{stem}_sample_dataset.csv'\n\n"
                "dataset_manifest = validate_dataset(records)\n"
                "CLASSES = dataset_manifest['classes']\n"
                "missing_prompts = [c for c in CLASSES if c not in class_prompts]\n"
                "extra_prompts = sorted(set(class_prompts) - set(CLASSES))\n"
                "if missing_prompts or extra_prompts:\n"
                "    raise ValueError(f'BYOD_CLASS_PROMPTS must name exactly the labels found {{CLASSES}}: missing {{missing_prompts}}, not in the data {{extra_prompts}}')\n"
                "per_class_minimum = minimum_records_per_class(len(CLASSES), VAL_FRACTION, TEST_FRACTION)\n"
                "splits = split_dataset(records, val_fraction=VAL_FRACTION, test_fraction=TEST_FRACTION, seed=SEED)\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "write_dataset_csv(records, dataset_csv)\n"
                "if USE_BYOD:\n"
                "    located = sum(has_location(r['image_bytes']) for r in records)\n"
                "    if located:\n"
                "        print(f'WARNING: {{located}} of your photographs carry an EXIF GPS block; their copies in outputs/byod/images/ keep it. Remove outputs/byod/ before sharing outputs/.')\n\n"
                "print({{'data_source': data_source, 'n_records': dataset_manifest['n_records'], 'classes': CLASSES, 'class_counts': dataset_manifest['class_counts']}})\n"
                "print({{'class_prompts': class_prompts, 'validation': dataset_manifest['validation']}})\n"
                "print({{'image_width': dataset_manifest['image_width'], 'image_height': dataset_manifest['image_height'], 'ceilings': dataset_manifest['ceilings'], 'digest': dataset_manifest['digest'][:16] + '...'}})\n"
                "print({{'train': len(train_records), 'validation': len(val_records), 'test': len(test_records), 'minimum_per_class_for_these_fractions': per_class_minimum, 'dataset_csv': dataset_csv}})\n"
                "if not USE_BYOD:\n"
                "    print({{'provenance': sample_provenance()}})\n\n"
                "thumb, per_row = 96, 12\n"
                "shown = records[:48]\n"
                "sheet = Image.new('RGB', (per_row * thumb, ((len(shown) + per_row - 1) // per_row) * thumb), 'white')\n"
                "for i, r in enumerate(shown):\n"
                "    sheet.paste(decode_image(r['image_bytes']).resize((thumb, thumb)), ((i % per_row) * thumb, (i // per_row) * thumb))\n"
                "sheet.save('outputs/{stem}_contact_sheet.png')\n"
                "try:\n"
                "    display(sheet)\n"
                "except NameError:\n"
                "    print('contact sheet written to outputs/{stem}_contact_sheet.png')"
            ),
        },
        {
            "md": (
                "**What to notice:** the split sizes, the per-class minimum printed beside them, and that the dataset digest is "
                "fixed for the sample (`f8fc68cf…`).\n\n"
                "<details><summary>Check your reasoning</summary>Per species, validation gets round(12 × 0.2) = 2, test gets "
                "round(12 × 0.25) = 3 and training keeps the other 7: 28 / 8 / 12 over four species. The smallest workable class "
                "is 5 photographs (1 validation, 1 test, 3 training); with only two classes it is 7, because the training split "
                "must also hold 8 photographs in total. A BYOD class below that is refused here, naming the class and the minimum, "
                "instead of failing four sections later.</details>\n\n"
                "## 5. What the input validation accepts and refuses\n\n"
                "`validate_inputs` decodes each image with Pillow, records its size and SHA-256, and raises exactly what "
                "`embed_images` or `classify` would raise. The ceilings are the checkpoint's and the runtime's, not biology's: a "
                "shorter side of at least `MIN_IMAGE_SIDE` px, a longer side of at most `MAX_IMAGE_SIDE` px, JPEG/PNG/WEBP, at "
                "most `MAX_IMAGES_PER_CALL` images per call and `MAX_LABELS` labels per zero-shot call. The cell shows three "
                "refusals — undecodable bytes, an unsupported format, a too-small image — and one acceptance. What it cannot "
                "show is a *semantic* refusal, because there is none: the schema says so in words.\n\n"
                "**Predict before running:** a 16x16 JPEG is a perfectly valid file. Will it be accepted, and if not, which rule "
                "refuses it?"
            ),
            "code": (
                "print({{'max_images_per_call': MAX_IMAGES_PER_CALL, 'image_side_pixels': [MIN_IMAGE_SIDE, MAX_IMAGE_SIDE], 'accepted_formats': list(ACCEPTED_FORMATS), 'max_labels': MAX_LABELS, 'image_size': IMAGE_SIZE}})\n"
                "print({{'validation': INPUT_SCHEMA['validation']}})\n\n"
                "def encoded(image, fmt):\n"
                "    buf = io.BytesIO()\n"
                "    image.save(buf, fmt)\n"
                "    return buf.getvalue()\n\n"
                "probes = {{\n"
                "    'garbage bytes': b'not an image',\n"
                "    'BMP file': encoded(Image.new('RGB', (64, 64), (200, 30, 30)), 'BMP'),\n"
                "    '16x16 image': encoded(Image.new('RGB', (16, 16)), 'JPEG'),\n"
                "}}\n"
                "for name, payload in probes.items():\n"
                "    try:\n"
                "        validate_inputs([payload])\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})\n\n"
                "input_manifest = validate_inputs([r['image_bytes'] for r in test_records[:4]], names=[r['id'] for r in test_records[:4]])\n"
                "print({{'verdict': input_manifest['verdict'], 'n_images': input_manifest['n_images'], 'requires_remote_code': input_manifest['requires_remote_code'], 'first': input_manifest['inputs'][0]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** each refusal names the rule it broke, and the accepted images are described by size and "
                "digest only.\n\n"
                "<details><summary>Check your reasoning</summary>It is refused by the size rule: its shorter side, 16 px, is "
                "below `MIN_IMAGE_SIDE` (32 px). Decoding succeeds, so the format is fine; the ceiling exists because the CLIP "
                "transform would upsample 16 px into 224 px of blur. Nothing in this cell looks at what the picture "
                "shows.</details>\n\n"
                "## 6. Image embeddings (representation, not prediction)\n\n"
                "`pipe.embed_images` runs the verified image tower and returns one L2-normalised 768-dimensional vector per "
                "image — a point in the joint image/text space. Embeddings are representations: they carry no label and no metric "
                "of their own; a downstream task is what gives them meaning (EVAL9). The cell embeds the eight validation images, "
                "writes them with their ids to `outputs/{stem}_embeddings.csv` (OUT4), and prints the mean cosine similarity "
                "within and between species as an inspection, not an evaluation.\n\n"
                "It also checks reproducibility the honest way: calling the same batch twice returns identical vectors, and "
                "embedding one of those images on its own differs only by float noise — accumulation order changes with the "
                "batch, which is noise, not stochasticity. A reader who needs bit-identical embeddings across batch sizes must "
                "fix the batch composition.\n\n"
                "**Predict before running:** will embedding one image on its own give exactly the same 768 numbers as embedding "
                "it inside a batch of eight?"
            ),
            "code": (
                "import csv\n"
                "import math\n\n"
                "embed_records = val_records[:8]\n"
                "embedding_result = pipe.embed_images([r['image_bytes'] for r in embed_records], names=[r['id'] for r in embed_records])\n"
                "vectors = embedding_result['embeddings']\n"
                "print({{'n_images': embedding_result['n_images'], 'dimension': embedding_result['dimension'], 'pooling': embedding_result['pooling'], 'norm_of_first': round(math.sqrt(sum(x * x for x in vectors[0])), 6)}})\n\n"
                "repeat = pipe.embed_images([r['image_bytes'] for r in embed_records], names=[r['id'] for r in embed_records])['embeddings']\n"
                "single = pipe.embed_images([embed_records[0]['image_bytes']])['embeddings'][0]\n"
                "cross_batch = max(abs(a - b) for a, b in zip(single, vectors[0]))\n"
                "print({{'same_batch_twice_identical': repeat == vectors, 'single_vs_batch_max_abs_diff': cross_batch, 'note': 'batch composition changes float accumulation order; this is float noise, not stochastic inference'}})\n"
                "assert repeat == vectors\n"
                "assert cross_batch < 1e-5\n\n"
                "def cosine(a, b):\n"
                "    return sum(x * y for x, y in zip(a, b)) / (math.sqrt(sum(x * x for x in a)) * math.sqrt(sum(y * y for y in b)))\n\n"
                "within, between = [], []\n"
                "for i in range(len(embed_records)):\n"
                "    for j in range(i + 1, len(embed_records)):\n"
                "        (within if embed_records[i]['label'] == embed_records[j]['label'] else between).append(cosine(vectors[i], vectors[j]))\n"
                "print({{'mean_cosine_within_species': round(sum(within) / len(within), 4) if within else None, 'mean_cosine_between_species': round(sum(between) / len(between), 4) if between else None, 'note': 'inspection only; embeddings are unlabelled representations'}})\n\n"
                "with open('outputs/{stem}_embeddings.csv', 'w', encoding='utf-8', newline='') as f:\n"
                "    writer = csv.writer(f)\n"
                "    writer.writerow(['id', 'label', 'sha256'] + [f'dim_{{k}}' for k in range(embedding_result['dimension'])])\n"
                "    for r, meta, vec in zip(embed_records, embedding_result['images'], vectors):\n"
                "        writer.writerow([r['id'], r['label'], meta['sha256']] + [f'{{x:.6f}}' for x in vec])\n"
                "print('wrote outputs/{stem}_embeddings.csv')"
            ),
        },
        {
            "md": (
                "**What to notice:** `same_batch_twice_identical` is `True`, `single_vs_batch_max_abs_diff` is tiny but usually "
                "not zero, and the within-species cosine is higher than the between-species one.\n\n"
                "<details><summary>Check your reasoning</summary>Not exactly. The same batch twice is bit-identical, but one "
                "image alone differs from its batched self by float noise: the cell only asserts the difference is below 1e-5, "
                "which every recorded run has met. The vector is the same point for any practical purpose; it is not the same "
                "bits, so compare embeddings with a tolerance, never with `==`.</details>\n\n"
                "## 7. Zero-shot species classification — the model's own prior\n\n"
                "`pipe.zero_shot` embeds one prompt per label (`PROMPT_TEMPLATE` with the scientific name filled in; `a photo of "
                "<scientific name>.` by default, BioCLIP's convention), embeds the images, and takes a softmax over the cosine "
                "similarities multiplied by the checkpoint's **logit scale** (100). No training is involved: this is what the "
                "pretrained model already knows about these species, and it is the baseline the fine-tuning in Section 9 must be "
                "read against. `zero_shot_evaluate` scores the whole test split this way.\n\n"
                "Three probes make the score semantics concrete (UNC1–UNC4). The scores are a softmax over **the label set you "
                "supplied and nothing else**: a blank grey image and a noise image still receive a confident label, because "
                "closed-set zero-shot always answers. An open-set probe — the same sparrow photo against `a rock`, `a car`, its "
                "species and `a domestic cat` — shows the model choosing the species. And common names are tried alongside "
                "scientific names, because which vocabulary the text tower knows best is an empirical question on your taxa.\n\n"
                "**Optional experiment:** change `PROMPT_TEMPLATE` below (for example `a photo of the bird {{}}.`; it must keep "
                "one `{{}}`), then select this cell and choose **Runtime → Run after**: Sections 7–13 re-run with the new prompts, "
                "and Section 9 initialises the head from them.\n\n"
                "**Predict before running:** a uniform grey image shows no bird at all. What will the top score be — near 0.25 "
                "(one in four) or well above it?"
            ),
            "code": (
                "PROMPT_TEMPLATE = 'a photo of {{}}.'  # @param {{type:\"string\"}}\n"
                "if PROMPT_TEMPLATE.count('{{}}') != 1:\n"
                "    raise ValueError('PROMPT_TEMPLATE must contain exactly one {{}} where the scientific name goes, for example \"a photo of {{}}.\"')\n\n"
                "baseline_zero_shot = pipe.zero_shot_evaluate(test_records, class_prompts, template=PROMPT_TEMPLATE)\n"
                "print({{k: baseline_zero_shot[k] for k in ('baseline', 'template', 'n', 'accuracy', 'macro_f1', 'auroc')}})\n"
                "for cls_name, row in baseline_zero_shot['per_class'].items():\n"
                "    print({{'class': cls_name, 'prompt': PROMPT_TEMPLATE.format(class_prompts[cls_name]), **row}})\n\n"
                "if not USE_BYOD:\n"
                "    common = pipe.zero_shot_evaluate(test_records, SAMPLE_COMMON_NAMES, template=PROMPT_TEMPLATE)\n"
                "    print({{'with_common_names': {{k: common[k] for k in ('accuracy', 'macro_f1')}}, 'note': 'same images, common names in the prompt instead of scientific names'}})\n\n"
                "example = test_records[0]\n"
                "single = pipe.zero_shot([example['image_bytes']], class_prompts, names=[example['id']], template=PROMPT_TEMPLATE)\n"
                "print({{'id': example['id'], 'true_label': example['label'], 'predicted': single['predictions'][0]['label'], 'scores': {{k: round(v, 4) for k, v in single['predictions'][0]['scores'].items()}}, 'logit_scale': round(single['logit_scale'], 2)}})\n"
                "print({{'decision_rule': single['decision_rule']}})\n\n"
                "open_set = pipe.zero_shot([example['image_bytes']], ['a rock', 'a car', class_prompts[example['label']], 'a domestic cat'], template=PROMPT_TEMPLATE)\n"
                "print({{'open_set_probe': {{k: round(v, 4) for k, v in open_set['predictions'][0]['scores'].items()}}}})\n\n"
                "blank = encoded(Image.new('RGB', (IMAGE_SIZE, IMAGE_SIZE), (128, 128, 128)), 'JPEG')\n"
                "import random\n"
                "rnd = random.Random(0)\n"
                "noise = encoded(Image.frombytes('RGB', (IMAGE_SIZE, IMAGE_SIZE), bytes(rnd.getrandbits(8) for _ in range(IMAGE_SIZE * IMAGE_SIZE * 3))), 'JPEG')\n"
                "for name, payload in (('blank grey image', blank), ('uniform noise image', noise)):\n"
                "    p = pipe.zero_shot([payload], class_prompts, template=PROMPT_TEMPLATE)['predictions'][0]\n"
                "    print({{'probe': name, 'label': p['label'], 'score': round(p['score'], 4), 'note': 'closed-set zero-shot always answers; a confident label is not evidence of a bird'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the test accuracy from names alone, the gap between scientific and common names, and the "
                "scores the blank and noise images receive.\n\n"
                "<details><summary>Check your reasoning</summary>Well above one in four: in the recorded runs the blank grey "
                "image got 0.53 and the noise image 0.85 for a single species. The softmax spreads 1.0 over the four names you "
                "supplied and has no \"none of these\" option, and the logit scale of 100 turns small cosine differences into "
                "large score differences. A high score therefore says \"this name fits better than the other three\", never "
                "\"this is a bird\". On the sample, zero-shot gets all 12 test photographs right.</details>\n\n"
                "## 8. Trivial baselines on the test split\n\n"
                "Two predictors that know nothing about birds set the floor (EVAL10/EVAL11). `majority_baseline` predicts the most "
                "frequent training class — 0.25 on a balanced four-class split. `color_baseline` reduces each image to six numbers "
                "(mean and standard deviation of R, G and B on a 32x32 thumbnail), fits one centroid per class on the **training "
                "split only** (SPL8) and assigns each test image to the nearest centroid.\n\n"
                "Colour is the confounder worth ruling out in a species task, and the four species were chosen to make it weak. "
                "On your own data, read this baseline first: if colour already separates your classes — a red bird versus a "
                "yellow one, or two species photographed against different backgrounds — a model can score well without having "
                "seen any structure.\n\n"
                "**Predict before running:** what accuracy will six colour numbers reach on four streaked brown sparrows?"
            ),
            "code": (
                "baseline_majority = majority_baseline(train_records, test_records, CLASSES)\n"
                "print({{k: baseline_majority[k] for k in ('baseline', 'predicted_label', 'accuracy', 'macro_f1')}})\n"
                "baseline_color = color_baseline(train_records, test_records, CLASSES)\n"
                "print({{k: baseline_color[k] for k in ('baseline', 'accuracy', 'macro_f1')}})\n"
                "print({{'centroids_rgb_mean': {{c: v[:3] for c, v in baseline_color['centroids'].items()}}, 'note': 'six-number colour space; fitted on the training split only'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** both baselines sit near 0.25, far below zero-shot.\n\n"
                "<details><summary>Check your reasoning</summary>Chance. In the recorded runs the colour baseline scored 0.25 "
                "accuracy (macro-F1 0.19) on the sample's test split — no better than predicting the majority class. That is the "
                "design: the species were chosen so colour cannot separate them, so zero-shot's score cannot be explained by "
                "colour. On your own data this number can be high, and then a high model score proves much less.</details>\n\n"
                "## 9. Bounded fine-tuning, starting from the zero-shot classifier\n\n"
                "A **linear head** — one weight vector and one bias per class — sits on the frozen image tower's L2-normalised "
                "features. It starts *as* the zero-shot classifier: each class's weight vector is that class's text embedding "
                "multiplied by the logit scale, so before any training it makes exactly the zero-shot predictions. Those starting "
                "weights are large (about 2.9 on average, because of the factor 100), and a learning rate is a step size, so a "
                "rate that is small relative to the weights cannot move them: at a single rate of 1e-4 the head moved by 0.02 % "
                "and stayed the zero-shot classifier whatever the data.\n\n"
                "So `select_head` trains the head at every rate of a grid fixed in advance — `LEARNING_RATES` = 1e-4, 1e-3 and "
                "1e-2 — for `EPOCHS` passes over features the frozen tower computes once, all from the same zero-shot start and "
                "seed, and keeps the **(rate, epoch) with the lowest validation cross-entropy**. Epoch 0, the zero-shot classifier "
                "itself, is a candidate for every rate, so \"training changed nothing\" can win and is then reported as such "
                "(`head_equals_zero_shot`). Validation chooses; the test split is never looked at (EVAL14). Training loss going "
                "down is optimisation evidence, not task-quality evidence (FT7) — Section 10 is where quality is measured. The "
                "record also reports how far the kept head moved from zero-shot (`relative_weight_change`) and how many "
                "training and validation predictions it changed. This is the procedure the Philippine capstone in this "
                "repository uses.\n\n"
                "**Optional experiment:** `TRAINABLE_BLOCKS = 1` unfreezes the last of the 24 tower blocks — 12.6 million more "
                "parameters — and trains them with the head at the single rate `BLOCK_LEARNING_RATE` for `BLOCK_EPOCHS`, keeping "
                "the final epoch, through `pipe.adapt`. Set it here, then select this cell and choose **Runtime → Run after** "
                "(Sections 9–13 re-run; Sections 10–11 then evaluate and export the block-trained model, and the export is about "
                "50 MB instead of 12 KB). It is not a like-for-like comparison with the default — one fixed rate, no validation "
                "selection, a tower that sees 28 images — so read it as \"what unfreezing a block does to a few dozen photographs\", "
                "not as a ranking of the two methods. On the sample the recorded result was 11/12 on the test split.\n\n"
                "**Predict before running:** on the sample, zero-shot is already right on all eight validation photographs. "
                "Will validation keep epoch 0, or choose a trained head — and if a trained head, will any prediction change?"
            ),
            "code": (
                "import time\n\n"
                "EPOCHS = 20  # @param {{type:\"integer\"}}\n"
                "BATCH_SIZE = 8  # @param {{type:\"integer\"}}\n"
                "TRAINABLE_BLOCKS = 0  # @param {{type:\"integer\"}}\n"
                "BLOCK_EPOCHS = 4  # @param {{type:\"integer\"}}\n"
                "BLOCK_LEARNING_RATE = 1e-4  # @param {{type:\"number\"}}\n\n"
                "started = time.perf_counter()\n"
                "if TRAINABLE_BLOCKS == 0:\n"
                "    adapt_result = select_head(\n"
                "        pipe,\n"
                "        train_records,\n"
                "        val_records,\n"
                "        classes=CLASSES,\n"
                "        class_prompts=class_prompts,\n"
                "        template=PROMPT_TEMPLATE,\n"
                "        epochs=EPOCHS,\n"
                "        learning_rates=LEARNING_RATES,\n"
                "        batch_size=BATCH_SIZE,\n"
                "        seed=SEED,\n"
                "    )\n"
                "else:\n"
                "    adapt_result = pipe.adapt(\n"
                "        train_records,\n"
                "        val_records,\n"
                "        classes=CLASSES,\n"
                "        class_prompts=class_prompts,\n"
                "        template=PROMPT_TEMPLATE,\n"
                "        epochs=BLOCK_EPOCHS,\n"
                "        learning_rate=BLOCK_LEARNING_RATE,\n"
                "        batch_size=BATCH_SIZE,\n"
                "        trainable_blocks=TRAINABLE_BLOCKS,\n"
                "        seed=SEED,\n"
                "    )\n"
                "adapt_seconds = round(time.perf_counter() - started, 2)\n"
                "print({{'method': adapt_result['method'], 'head_initialisation': adapt_result['head_initialisation'], 'trainable_parameters': adapt_result['trainable_parameters'], 'total_parameters': adapt_result['total_parameters'], 'precision': adapt_result['precision'], 'device': pipe.device, 'seconds': adapt_seconds}})\n"
                "if 'selected' in adapt_result:\n"
                "    for rate in adapt_result['learning_rate_grid']:\n"
                "        rows = [h for h in adapt_result['history'] if h['learning_rate'] == rate]\n"
                "        best = min(rows, key=lambda h: (h['val_loss'], h['epoch']))\n"
                "        print({{'learning_rate': rate, 'val_loss_epoch_0': rows[0]['val_loss'], 'best_epoch': best['epoch'], 'best_val_loss': best['val_loss'], 'val_accuracy_at_best': best['val_accuracy'], 'val_loss_last_epoch': rows[-1]['val_loss']}})\n"
                "    print({{'selected': adapt_result['selected'], 'head_equals_zero_shot': adapt_result['head_equals_zero_shot']}})\n"
                "    print({{'head_change': adapt_result['head_change']}})\n"
                "else:\n"
                "    for step in adapt_result['history']:\n"
                "        print(step)"
            ),
        },
        {
            "md": (
                "**What to notice:** which rate won, at which epoch, and the `head_change` line — `relative_weight_change` (how "
                "far the weights moved, as a fraction of their starting size) and `predictions_changed_vs_zero_shot`.\n\n"
                "<details><summary>Check your reasoning</summary>In a local Windows CPU check of this version, validation chose "
                "rate 1e-2 at epoch 6 (validation cross-entropy 0.0116 against 0.0203 at epoch 0). Accuracy cannot rise above "
                "8/8, but cross-entropy can still fall: the head becomes more confident in answers that were already right. The "
                "weights moved by about 2 % and **no** training or validation prediction changed. So on this sample fine-tuning "
                "sharpens the zero-shot classifier without changing what it decides — compare Section 13, where the names carry "
                "no information and the same procedure changes a great deal.</details>\n\n"
                "## 10. Held-out evaluation\n\n"
                "`pipe.evaluate` classifies every image of a split with the adapted head and reports `accuracy`, `macro_f1` (the "
                "unweighted mean of per-class F1, which exposes a model that ignores a class), per-class precision/recall/F1 with "
                "support, and `auroc` (macro one-vs-rest, ranking quality independent of the argmax). The **test split** was never "
                "used for training or selection, so its numbers are the independent evidence (SPL6/SPL7). These are tutorial "
                "metrics on a small split (EVAL6): one holdout, no dispersion estimate. The cell also counts how many test "
                "predictions equal zero-shot's. The report — with the zero-shot, majority and colour baselines, the deltas against "
                "them and the full adaptation record — is written to `outputs/{stem}_evaluation_report.json`.\n\n"
                "Read the delta against **zero-shot** first, together with the agreement count. A delta of zero with full "
                "agreement means the adapted model decides exactly as zero-shot does; a delta of zero is *not* by itself proof "
                "that training did nothing — Section 9's `head_change` says how far the head moved.\n\n"
                "**Predict before running:** can the test accuracy delta against zero-shot be positive on the sample?"
            ),
            "code": (
                "val_metrics = pipe.evaluate(val_records)\n"
                "test_metrics = pipe.evaluate(test_records)\n"
                "print({{'split': 'validation', **{{k: val_metrics[k] for k in ('n', 'accuracy', 'macro_f1', 'auroc')}}}})\n"
                "print({{'split': 'test', **{{k: test_metrics[k] for k in ('n', 'accuracy', 'macro_f1', 'auroc')}}}})\n"
                "for cls_name, row in test_metrics['per_class'].items():\n"
                "    print({{'class': cls_name, **row}})\n\n"
                "zero_shot_labels, adapted_labels = [], []\n"
                "for start in range(0, len(test_records), MAX_IMAGES_PER_CALL):\n"
                "    chunk = [r['image_bytes'] for r in test_records[start : start + MAX_IMAGES_PER_CALL]]\n"
                "    zero_shot_labels += [p['label'] for p in pipe.zero_shot(chunk, class_prompts, template=PROMPT_TEMPLATE)['predictions']]\n"
                "    adapted_labels += [p['label'] for p in pipe.classify(chunk)['predictions']]\n"
                "agreement = {{'test_predictions_equal_to_zero_shot': sum(a == z for a, z in zip(adapted_labels, zero_shot_labels)), 'of': len(test_records)}}\n"
                "print(agreement)\n\n"
                "evaluation_report = {{\n"
                "    'task': 'species classification (bounded fine-tuning of a BioCLIP 2 head initialised from zero-shot)',\n"
                "    'evidence': 'tutorial sample-sanity metrics on one stratified holdout; not a benchmark',\n"
                "    'estimation': 'single train/validation/test split, seed ' + str(SEED) + ', no dispersion estimate',\n"
                "    'data_source': data_source,\n"
                "    'dataset_digest': dataset_manifest['digest'],\n"
                "    'classes': CLASSES,\n"
                "    'class_prompts': class_prompts,\n"
                "    'prompt_template': PROMPT_TEMPLATE,\n"
                "    'splits': {{'train': len(train_records), 'validation': len(val_records), 'test': len(test_records)}},\n"
                "    'baselines': {{'zero_shot': baseline_zero_shot, 'majority': baseline_majority, 'color': baseline_color}},\n"
                "    'validation_metrics': val_metrics,\n"
                "    'test_metrics': test_metrics,\n"
                "    'delta_vs_zero_shot': {{k: round(test_metrics[k] - baseline_zero_shot[k], 4) for k in ('accuracy', 'macro_f1')}},\n"
                "    'delta_vs_majority': {{k: round(test_metrics[k] - baseline_majority[k], 4) for k in ('accuracy', 'macro_f1')}},\n"
                "    'agreement_with_zero_shot': agreement,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k != 'trainable_parameter_names'}},\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report, f, indent=2)\n"
                "print({{'delta_vs_zero_shot': evaluation_report['delta_vs_zero_shot'], 'delta_vs_majority': evaluation_report['delta_vs_majority'], 'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the test accuracy, the delta against zero-shot and the agreement count.\n\n"
                "<details><summary>Check your reasoning</summary>No. Zero-shot is already right on all 12 test photographs, so "
                "there is no room above it: the delta can only be zero or negative. In the local CPU check of this version the "
                "adapted head scored 12/12 and agreed with zero-shot on all 12. That is a ceiling effect, not evidence that "
                "adaptation is useless — Section 13 removes the ceiling.</details>\n\n"
                "## 11. Inference on held-out images, artifact export and fresh reload\n\n"
                "`pipe.classify` returns, per image, the argmax `label`, its `score`, the full `scores` dictionary in class order "
                "and the image digest. The scores are softmax outputs of a head trained on a few dozen images — **not calibrated "
                "probabilities** (UNC2); the only decision rule is argmax (UNC3). The six inputs here are held-out test images the "
                "head never saw in training.\n\n"
                "`pipe.save_artifact` writes the trained tensors as `adapter.safetensors` — with the default head-only setting, "
                "one 768-number weight vector and one bias per class (about 12 KB for four classes) — with a `manifest.json` "
                "recording the artifact format, the base model id and revision, the class order, the tensor names, the file size "
                "and SHA-256, and the adaptation record including the learning-rate grid and the selection (OUT8). "
                "`BioClip2Pipeline.from_artifact` re-verifies the base snapshot, checks the artifact manifest and digests **before** "
                "deserialising, rebuilds the classifier and overlays the tensors — a fresh object from files, not the in-memory "
                "model (VER2). The cell asserts identical labels and scores within `1e-5` (VER4).\n\n"
                "**Predict before running:** the reloaded model is rebuilt from files on disk. Will its scores equal the "
                "in-memory model's exactly, or only approximately?"
            ),
            "code": (
                "new_records = test_records[:6]\n"
                "new_source = 'six held-out test-split images (never used for training or selection)'\n"
                "inference_result = pipe.classify([r['image_bytes'] for r in new_records], names=[r['id'] for r in new_records])\n"
                "predictions = inference_result['predictions']\n"
                "print({{'new_source': new_source, 'decision_rule': inference_result['decision_rule']}})\n"
                "n_match = 0\n"
                "for p, r in zip(predictions, new_records):\n"
                "    n_match += p['label'] == r['label']\n"
                "    print({{'id': p['id'], 'predicted': p['label'], 'score': round(p['score'], 4), 'true_label': r['label']}})\n"
                "print({{'matches': n_match, 'of': len(new_records), 'note': 'sanity check on held-out images, not an evaluation'}})\n\n"
                "with open('outputs/{stem}_predictions.csv', 'w', encoding='utf-8', newline='') as f:\n"
                "    writer = csv.writer(f)\n"
                "    writer.writerow(['id', 'sha256', 'predicted_label', 'score'] + [f'score_{{c}}' for c in CLASSES])\n"
                "    for p in predictions:\n"
                "        writer.writerow([p['id'], p['sha256'], p['label'], f\"{{p['score']:.6f}}\"] + [f\"{{p['scores'][c]:.6f}}\" for c in CLASSES])\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "pipe.save_artifact(artifact_dir, metadata={{'data_source': data_source, 'dataset_digest': dataset_manifest['digest'], 'test_metrics': {{k: test_metrics[k] for k in ('n', 'accuracy', 'macro_f1', 'auroc')}}}})\n"
                "with open(artifact_dir / ARTIFACT_MANIFEST_NAME, encoding='utf-8') as f:\n"
                "    artifact_manifest = json.load(f)\n"
                "print({{'format': artifact_manifest['format'], 'base_model': artifact_manifest['base_model'], 'requires_remote_code': artifact_manifest['requires_remote_code'], 'n_tensors': len(artifact_manifest['tensors']), 'tensors': artifact_manifest['tensors'], 'files': artifact_manifest['files']}})\n\n"
                "reloaded_pipe = BioClip2Pipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR)\n"
                "reloaded_result = reloaded_pipe.classify([r['image_bytes'] for r in new_records], names=[r['id'] for r in new_records])\n"
                "max_score_diff = 0.0\n"
                "for before, after in zip(predictions, reloaded_result['predictions']):\n"
                "    assert before['id'] == after['id'] and before['label'] == after['label'], f'reload parity failure on {{before[\"id\"]}}'\n"
                "    max_score_diff = max(max_score_diff, abs(before['score'] - after['score']))\n"
                "assert max_score_diff < 1e-5, f'reload score drift {{max_score_diff}}'\n"
                "print({{'reload_parity': 'PASS', 'labels_equal': True, 'max_abs_score_diff': max_score_diff}})"
            ),
        },
        {
            "md": (
                "**What to notice:** `reload_parity: PASS` and the size of `max_abs_score_diff`.\n\n"
                "<details><summary>Check your reasoning</summary>Exactly, here: the recorded runs report a maximum difference "
                "of 0.0, because the same float32 tensors are loaded into the same architecture on the same device. The cell "
                "still allows 1e-5, because a reload on a different device or library build may differ in the last float bits; "
                "a larger difference would mean the export and the evaluated model are not the same model.</details>\n\n"
                "## 12. Result export and provenance\n\n"
                "The last output, `outputs/{stem}_result.json`, gathers what a reader needs to interpret the files above: the "
                "notebook source revision, the model id, immutable revision and licence, the dataset source, digest and (for the "
                "sample) its iNaturalist provenance summary, the class prompts and prompt template, the adaptation record, the "
                "zero-shot and trivial baselines and held-out metrics, the held-out predictions, the artifact manifest, the "
                "reload-parity result, and the runtime versions and device (OUT6/OUT7). No credential is involved anywhere in this "
                "notebook, so none can leak into it (OUT10)."
            ),
            "code": (
                "import platform\n\n"
                "result_payload = {{\n"
                "    'task': 'species classification adaptation (BioCLIP 2)',\n"
                "    'pipeline_class': 'BioClip2Pipeline',\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'remote_code_executed': False,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'data_source': data_source,\n"
                "    'sample_provenance': None if USE_BYOD else sample_provenance(),\n"
                "    'dataset_manifest': dataset_manifest,\n"
                "    'class_prompts': class_prompts,\n"
                "    'prompt_template': PROMPT_TEMPLATE,\n"
                "    'embedding_summary': {{'n_images': embedding_result['n_images'], 'dimension': embedding_result['dimension'], 'pooling': embedding_result['pooling'], 'single_vs_batch_max_abs_diff': cross_batch}},\n"
                "    'evaluation_report': evaluation_report,\n"
                "    'inference': {{'new_source': new_source, 'decision_rule': inference_result['decision_rule'], 'predictions': predictions}},\n"
                "    'artifact_format': ARTIFACT_FORMAT,\n"
                "    'artifact_format_version': ARTIFACT_FORMAT_VERSION,\n"
                "    'artifact_manifest': artifact_manifest,\n"
                "    'reload_parity': {{'labels_equal': True, 'max_abs_score_diff': max_score_diff}},\n"
                "    'runtime': {{\n"
                "        'python': platform.python_version(),\n"
                "        'torch': torch.__version__,\n"
                "        'open_clip': open_clip.__version__,\n"
                "        'safetensors': safetensors.__version__,\n"
                "        'device': pipe.device,\n"
                "        'precision': 'float32',\n"
                "    }},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(result_payload, f, indent=2)\n\n"
                "print('outputs/:')\n"
                "for path in sorted(Path('outputs').rglob('*')):\n"
                "    if path.is_file():\n"
                "        print(f'  - {{path.as_posix()}} ({{path.stat().st_size / 1024:.1f}} KB)')"
            ),
        },
        {
            "md": (
                "## 13. Your turn — change one thing: uninformative class names\n\n"
                "On the sample, zero-shot is already perfect, so Sections 9–10 could only show that fine-tuning does no harm. "
                "This activity removes the ceiling without new data: it replaces each scientific name by an uninformative name "
                "(`species 0` … `species 3` with `ACTIVITY_NAMES = 'neutral'`), so the text tower knows nothing about the classes "
                "and the zero-shot start is close to guessing. Everything else is the default procedure — the same training and "
                "validation photographs, the same learning-rate grid and validation selection, the same seed — run with "
                "`fit_head` on image features computed once. It never touches the adapter exported in Section 11. Set "
                "`ACTIVITY_NAMES = 'common'` (sample only) or `'scientific'` and run this cell again to compare; every run is "
                "appended to a run-history table.\n\n"
                "**Predict →** before running, write down the zero-shot test accuracy you expect with names that mean nothing, "
                "and the test accuracy after fine-tuning. **Change** `ACTIVITY_NAMES` (it starts at `neutral`). **Run** this "
                "cell. **Observe** the two accuracies, the selected rate and epoch, and `predictions_changed_vs_zero_shot`. "
                "**Explain** why the same procedure that changed no prediction in Section 9 changes many here."
            ),
            "code": (
                "import numpy as np\n\n"
                "ACTIVITY_NAMES = 'neutral'  # @param [\"neutral\", \"common\", \"scientific\"]\n\n"
                "if ACTIVITY_NAMES == 'neutral':\n"
                "    activity_prompts = {{c: f'species {{i}}' for i, c in enumerate(CLASSES)}}\n"
                "elif ACTIVITY_NAMES == 'common' and not USE_BYOD:\n"
                "    activity_prompts = dict(SAMPLE_COMMON_NAMES)\n"
                "elif ACTIVITY_NAMES == 'scientific':\n"
                "    activity_prompts = dict(class_prompts)\n"
                "else:\n"
                "    raise ValueError(\"ACTIVITY_NAMES must be 'neutral', 'common' (sample only) or 'scientific'\")\n\n"
                "def split_features(split_records):\n"
                "    rows = []\n"
                "    for start in range(0, len(split_records), MAX_IMAGES_PER_CALL):\n"
                "        rows += pipe.embed_images([r['image_bytes'] for r in split_records[start : start + MAX_IMAGES_PER_CALL]])['embeddings']\n"
                "    return np.asarray(rows, dtype=np.float32)\n\n"
                "if 'activity_features' not in globals() or activity_features['dataset_digest'] != dataset_manifest['digest']:\n"
                "    activity_features = {{'dataset_digest': dataset_manifest['digest'], **{{name: split_features(part) for name, part in (('train', train_records), ('validation', val_records), ('test', test_records))}}}}\n"
                "index = {{c: i for i, c in enumerate(CLASSES)}}\n"
                "labels = {{name: np.asarray([index[r['label']] for r in part]) for name, part in (('train', train_records), ('validation', val_records), ('test', test_records))}}\n"
                "text = np.asarray(pipe.embed_texts([PROMPT_TEMPLATE.format(activity_prompts[c]) for c in CLASSES])['embeddings'], dtype=np.float32)\n"
                "tensors, history, selection = fit_head(activity_features['train'], labels['train'], activity_features['validation'], labels['validation'], text, pipe.logit_scale, epochs=EPOCHS, learning_rates=LEARNING_RATES, batch_size=BATCH_SIZE, seed=SEED)\n"
                "weight, bias = (np.asarray(tensors[k].detach().cpu().numpy()) for k in ('head.weight', 'head.bias'))\n"
                "zero_shot_test = float(np.mean((activity_features['test'] @ (text * pipe.logit_scale).T).argmax(1) == labels['test']))\n"
                "adapted_test = float(np.mean((activity_features['test'] @ weight.T + bias).argmax(1) == labels['test']))\n"
                "change = head_change(np.concatenate([activity_features['train'], activity_features['validation']]), tensors, text, pipe.logit_scale)\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append({{'names': ACTIVITY_NAMES, 'zero_shot_test_accuracy': round(zero_shot_test, 4), 'adapted_test_accuracy': round(adapted_test, 4), 'selected_rate': selection['learning_rate'], 'selected_epoch': selection['epoch'], 'relative_weight_change': round(change['relative_weight_change'], 4), 'predictions_changed_vs_zero_shot': change['predictions_changed_vs_zero_shot'], 'of': change['records_compared']}})\n"
                "print({{'activity_prompts': activity_prompts}})\n"
                "for row in run_history:\n"
                "    print(row)"
            ),
        },
    ],
    "closing": (
        "**What to notice:** the neutral-name run starts far below the scientific-name run and fine-tuning closes much of the "
        "gap; its `predictions_changed_vs_zero_shot` is large where Section 9's was zero.\n\n"
        "<details><summary>Check your reasoning</summary>In a local Windows CPU check of this version, neutral names gave a "
        "zero-shot test accuracy of 0.33; validation then chose rate 1e-2 at epoch 20, the weights moved by about 8 %, 17 of 36 "
        "training and validation predictions changed, and test accuracy rose to 0.92. With scientific names the same procedure "
        "moved the weights by about 2 % and changed nothing. Fine-tuning helps exactly where the starting classifier is wrong "
        "and the image features already separate the classes; it cannot add what the frozen features lack. Swapping the "
        "scientific names between classes is harder still: a confidently wrong start needs far more than 20 epochs to "
        "undo.</details>\n\n"
        "## Interpretation and limits\n\n"
        "The pretrained model separates four similarly coloured sparrow species from their scientific names alone, and a head "
        "fine-tuned from that starting point, with its learning rate and epoch chosen on validation, keeps the separation on an "
        "independent split while changing none of the predictions. That is the claim: BioCLIP 2's joint space already encodes "
        "fine-grained taxonomic structure that colour does not explain, and the adaptation procedure starts from that structure "
        "and reports how far it moves from it. The test split has 12 photographs, the metrics come from one seeded holdout with "
        "no dispersion estimate, and the four species are common, well-photographed North American birds — the easy end of "
        "biodiversity. So a perfect score on the default sample run says the contract works on this sample, not that BioCLIP 2 "
        "identifies rare, cryptic or poorly represented taxa, and not that it reproduces any published benchmark. Section 13 "
        "shows what the same procedure does when the starting classifier is poor; it is an exercise on renamed classes, not "
        "evidence about any real taxon.\n\n"
        "Three things to carry to real data. **Zero-shot first:** run `zero_shot_evaluate` on your labelled set before you "
        "train anything — if it is already saturated, adaptation has little to add, and if it is poor, check the prompt "
        "vocabulary (scientific versus common names, full taxonomic strings) before blaming the model. **Splits:** photographs of "
        "one individual, one photographer or one site leak across a random split; split by observation, site or photographer. "
        "**Read the head record:** a zero delta with `head_equals_zero_shot` true means training was not worth keeping; a zero "
        "delta with a moved head means training sharpened answers that were already right.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline modules, carried in this standalone "
        "notebook, can acquire and digest-verify the pinned model, build it from its pinned config, validate the demonstrated "
        "dataset contract, classify zero-shot, execute bounded fine-tuning with validation selection, evaluate against trivial "
        "baselines on an independent split, and emit the shown machine-readable artifacts — without the repository being "
        "reachable. It does **not** establish benchmark superiority, production fitness, or that any photograph shows what its "
        "label says.\n\n"
        "**Optional experiments (they do not affect the default path):** each names its field and the cells to re-run. "
        "`PROMPT_TEMPLATE` in Section 7 (for example `a photo of the bird {{}}.`), then **Run after** from Section 7. "
        "`TRAINABLE_BLOCKS = 1` in Section 9, then **Run after** from Section 9 (on the sample: 11/12 on the test split and a "
        "50 MB export). `ACTIVITY_NAMES` in Section 13, then run that cell. BYOD: `USE_BYOD`, `BYOD_PATH` and "
        "`BYOD_CLASS_PROMPTS` in Section 4, then **Run after** from Section 4, and read the zero-shot and colour baselines "
        "first.\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"This notebook needs a Linux x86_64 runtime\"** — you are on Windows, macOS or an ARM "
        "machine. Use Google Colab, Kaggle or a Linux x86_64 Jupyter server.\n"
        "- **The uv wheel fails its size/SHA-256 check, or a download times out** — run the cell again; if it repeats, the "
        "network is altering or blocking `files.pythonhosted.org`. The checkpoint download needs `huggingface.co`.\n"
        "- **\"The isolated environment's Python process exited\"** — usually out of memory: by Section 11 the base model, the "
        "adapted classifier's tower copy and the reloaded model are all resident. Restart the session and choose **Run all**; "
        "on a small CPU runtime prefer a GPU runtime.\n"
        "- **BYOD: \"no <label>/<image> files found\"** — the zip needs one folder per label holding that label's images, "
        "optionally inside one enclosing folder, or a single CSV/JSON/JSONL table of image paths.\n"
        "- **BYOD: \"supply at least N records per class\"** — a class is too small for the split; add photographs, or lower "
        "`VAL_FRACTION`/`TEST_FRACTION` (the message states the minimum for the fractions you set).\n"
        "- **BYOD: \"BYOD_CLASS_PROMPTS must name exactly the labels found\"** — give one scientific name for every folder "
        "name, and nothing else, as a JSON object.\n"
        "- **BYOD: \"is an MPO file\"** — re-save that photograph as a plain JPEG and upload again.\n"
        "- **BYOD: \"Upload exactly one .zip file\"** — the dialog was cancelled or several files were chosen; run Section 4 "
        "again.\n\n"
        "## Glossary\n\n"
        "- **Zero-shot classification** — classifying with no training: each image is compared with the text embedding of each "
        "class name and the closest name wins.\n"
        "- **Prompt template** — the sentence the class name is put into before it is embedded (`a photo of {{}}.`).\n"
        "- **Embedding** — a vector the model produces for an image or a text; here unit length, 768 numbers, comparable by "
        "cosine similarity.\n"
        "- **Logit scale** — the factor (100 for this checkpoint) that multiplies cosine similarities before the softmax; it "
        "makes small similarity differences into confident scores.\n"
        "- **Softmax score** — scores that sum to 1 over the classes you supplied; a ranking signal, not a calibrated "
        "probability.\n"
        "- **Linear head** — one weight vector and one bias per class on top of frozen features; here it starts as the "
        "zero-shot classifier.\n"
        "- **Learning rate / epoch** — the step size of each update, and one pass over the training photographs.\n"
        "- **Validation selection** — choosing settings (here the rate and the epoch) by a split that is neither trained on nor "
        "used for the final evaluation.\n"
        "- **Cross-entropy** — the average of −log(score of the true class); lower means more confident and right.\n"
        "- **Macro-F1** — the unweighted mean of per-class F1, so a class the model ignores pulls it down.\n"
        "- **AUROC** — how well the scores rank the true class above the others (1.0 perfect, 0.5 chance), independent of the "
        "argmax.\n"
        "- **Reload parity** — the exported adapter, loaded from disk into a fresh pipeline, gives the same predictions.\n"
        "- **BYOD** — bring your own data: your labelled photographs through the same cells.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional — fill in for yourself:\n\n"
        "- On my run, zero-shot test accuracy was ___, the colour baseline ___ and the adapted head ___.\n"
        "- Validation chose rate ___ at epoch ___; the head moved by ___ % and changed ___ predictions.\n"
        "- In Section 13, neutral names gave ___ before and ___ after fine-tuning, because ___.\n"
        "- One thing I would check before trusting these numbers on my own data: ___.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/bioclip2-biodiversity-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/bioclip2-biodiversity-pipeline/blob/main/MODEL_CARD.md\n"
        "- Upstream model: https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code: https://github.com/Imageomics/bioclip-2\n"
        "- Gu, J., Stevens, S., Campolongo, E. G., et al. (2025). BioCLIP 2: Emergent Properties from Scaling Hierarchical "
        "Contrastive Learning. NeurIPS 2025. arXiv:2505.23883. https://arxiv.org/abs/2505.23883\n"
        "- Sample photographs: iNaturalist research-grade observations with CC0 1.0 photo licences; per-image observation URLs "
        "are recorded in the carried `sample_data` module."
    ),
}
